### ISSUE TITLE
should invocation_hash include the method name?

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/wasmcloud-otp#127]
There is a small possibility that invocations of different functions between the same two entities could produce the same invocation hash. It's not a very high likelihood, but it is made more likely by the fact that functions that take no parameters (such as `clear()`, `init()`) between the same two entities would have the same hash, because the message for all of them  is a zero-byte array. 

Adding the method name to the hash would give this function what I believe are its intended uniqueness properties.

(If there's a timestamp or per-message id  that I'm not seeing in the code, the hash would be unique and this would be a non-issue).

**Comment by autodidaddict** [comment]
@stevelr the hash isn't there to guarantee uniqueness, it's there to ensure that the message itself hasn't been tampered with. Having the raw message bytes as part of the hash feels good enough because what we're trying to do is ensure the payload and target hasn't been altered by a malicious actor. 

I'm okay with adding the operation name to the hash, but it feels a bit unnecessary considering the goals of the hash. 

Thoughts?

**Comment by autodidaddict** [comment]
The more I think about this the more I like the idea of including the operation name in the hash.
