### ISSUE TITLE
[BUG] Live update does not update internal ociref state

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wasmcloud-otp#238]
When we perform a live update, the live update can fail for two reasons
1. If using a localhost registry, the live update can fail without the `WASMCLOUD_OCI_ALLOWED_INSECURE` flag. This should be reflected in our documentation https://github.com/wasmCloud/wasmcloud-dev-site/issues/68
2. The live update does not update the ActorModule internal state to reflect the new OCI reference. This internal state is used later on during scale events, and will fail with the following error:
```
Error scaling actor: Error: Cannot start MBCFOPM6JW2APJLXJD3Z5O4CN7CPYJ2B4FTKLJUR5YR5MITIU7HD3WD5 - the OCI reference 'wasmcloud.azurecr.io/echo:0.3.1' does not match a pre-existing cache. To upgrade an actor, use live update.
```

The live update will work initially, but then fail any following scale events. When a live update is performed, we should also update the ociref to reflect the new ociref.

**Comment by autodidaddict** [comment]
ActorModule internal `ociref` field state is not used in determining whether or not an actor can be lived updated, that's handled by the OCI ref distributed cache.

**Comment by autodidaddict** [comment]
Ok so after looking at this, it seems like there's a relatively minor change in logic that will fix quite a few edge cases.

Old logic: examine the _distributed cache_ for pre-existing OCI references and, if there is at least one, deny an actor the ability to start.

New logic: examine the _running actors_ for pre-existing OCI reference and, if there is at least one, deny the candidate actor the ability to start. This works out properly because the OCI refmap cache grows indefinitely, whereas there should only ever be a single OCI reference for a given actor in use on a host at any given time.
