### ISSUE TITLE
Build `host_core` only Docker image

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wasmcloud-otp#253]
While writing the Helm chart to spin up wasmCloud hosts in k8s, I realized that someone running it for realz in k8s would probably not need all the dashboard assets and what not included in every single running host. Ideally, there would be 2 different deployments: One that can scale up hosts (without dashboards included) and one that is a single replica running the dashboard included version.

We should also build and push a `host_core` only Docker image and tarballs for people who don't need the dashboard included in situations like this

**Comment by brooksmtownsend** [comment]
> Minor point: In that scenario might be able to save a little extra space by removing python 2, node, and npm.

One thing to note about that, we do use node+npm+python on the install section of the docker image, but the distributed image in the end is a `debian:buster-slim` with minimal dependencies, so we're pretty minimal as-is (though using a scratch image and copying shared objects over would be the actual minimal size.)

Because of our previous discussion, I'm going to go ahead and close this issue since distributing `host_core` wouldn't improve our image/tarball distribution size by more than 10%.
