### ISSUE TITLE
start actor in the web ui fails to load when actor's size is large

### ISSUE THREAD

**Issue by alanpoon** [wasmCloud/wasmcloud-otp#267]
If actor's size larger than 2mb, start actor in the web ui fails to load.
<img width="494" alt="Screenshot 2021-11-09 at 11 31 11 PM" src="https://user-images.githubusercontent.com/8205468/140954177-725a1573-9418-4bcc-b0f0-e32c9d93b454.png">
d.

**Comment by autodidaddict** [comment]
Could you possibly share the `.wasm` binary that you're using for this? Did you upload the actor or point to an OCI registry?

**Comment by brooksmtownsend** [comment]
According to https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#allow_upload/3, the maximum filesize is set at 8MB by default. From my testing if you compile a Rust actor in debug mode (I used `echo`) it can exceed 8MB. Because debug mode can be useful for development, I propose upping this limit to 16MB and giving the user a better error message so that we can easily determine the source of this bug in the future.

**Comment by alanpoon** [comment]
[prelude.wasm.zip](https://github.com/wasmCloud/wasmcloud-otp/files/7521061/prelude.wasm.zip)
I will try also again on my side

**Comment by brooksmtownsend** [comment]
@alanpoon try it out again with the latest stuff in `main`, my last PR should have fixed your issue unless the actor is >16MB
