### ISSUE TITLE
[RFC] Validate anti-forgery tokens on inbound invocations

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#34]
# Validating Anti-Forgery Tokens
This RFC was originally a simple implementation issue but, after much discussion, we think it needs some more commentary before we implement (or don't) anything.

## Current State
In the current (`v0.18.x`) state of things, when a capability provider sends an invocation to an actor, it sends a raw payload to the wasmCloud host. The host then wraps that in an invocation, _signs it_ with the host's private key, and then delivers the invocation directly to the actor. 

Conversely, when an actor makes a _host call_, the call bubbles up as a raw payload, which is then wrapped in an invocation and then _signed_ by the host's private key. There is a set of claims on the invocation itself that are signed, which include the target URL, the origin URL, and the operation name. This is, in theory, designed to prevent anyone who has compromised the system from sending fake invocations.

The current state of things requires that both actors and capability providers send raw  payloads _through_ the host, which signs the invocation prior to publication across a network. Upon receipt _from_ the network, the destination host will then perform a signature verification against the signed claims on the invocation.

## Proposed Solution
The proposed solution is to, quite simply, _do nothing_. Capability providers are able to send invocations _directly_ to actors via NATS in the `0.20.x` versions and later, taking the host out of the communication channel as an unnecessary "person in the middle."

The assumption in the proposed solution is that if a malicious entity compromises enough of the system to have full and unfettered access to the NATS server (it has a valid TLS connection to NATS using a valid user JWT and valid user seed), then asking the provider or actor to sign their invocations is nothing more than theater.

Further, in the new (`v0.20.x`) version, capability providers and actors _do not have_ access to the host's signing key. This quite literally means that it's _impossible_ for a capability provider to generate signed credentials without an alternate key, like possibly the provider's signing key or the actor's signing key. This would require private keys to be floating around in the system in violation of our requirement that no long-term private keys are ever deployed to production. 

## Alternatives Considered
There are actually only a few options here:
* Burden capability providers with the need to sign invocations they send, using their own signing keys or signing keys devoted solely to the need for invocation anti-forgery tokens, or possibly even something as complex as **TUF** (the update framework).
* Do not require capability providers to sign their invocations, assuming that this kind of AFT verification is more theater than actual security.

We feel that asking capability providers and actors to sign their own invocations in such a way that can be verified by the host when the entities on either end of the transmission do _not_ have a host key is an even greater security risk than simply not requiring signed claims. Therefore we're thinking the latter option of _not_ using anti-forgery tokens actually speeds up performance and avoids wasting effort and code on a false security vector.

**Comment by brooksmtownsend** [comment]
This reminds me now of a vulnerability I had to fix on a Kubernetes cluster on my old team. The vulnerability was if you were ssh'ed onto a host machine, and had root access, then a specific set of commands would let them compromise the cluster. 
But honestly, they had root access on the control plane node already, what wasn't within reach already?

One of the big value props of elixir and executable capability providers is that we allow _more_ flexibility for the developer to write providers in different languages, and we'll be shooting ourselves in the foot to distribute a library for signing for all of the languages we support. Yeah, there's the whole theory that security is the inverse of usability, but I think as you mentioned that having access into a lattice would be a critical security flaw already.

What would be nice is to get some concrete implementations of NATS security federating access to a lattice, and making that aspect secure-by-default with wasmcloud. What I mean specifically is we should have some samples for running the nats-server instead of just in un-authenticated mode, as you would outside of a local developer environment. It feels like there's going to be a careful balance there between the initial developer experience and enforcing good security practices from the start, but with NATS auth as the primary bodyguard between a malicious actor, we don't want anyone to accidentally be running in anonymous authentication mode.

To clarify, all of my comments apply to the `0.18.x` version as well, https://wasmcloud.dev/app-dev/secure/

**Comment by autodidaddict** [comment]
Definitely agreed on all points. One of our samples should use leaf nodes and full, decentralized security (JWTs and seeds)

**Comment by brooksmtownsend** [comment]
There's certainly an opportunity for us to define those samples as "recommended authentication methods" and provide auto-generation with [wash](https://github.com/wasmcloud/wash) to configure defaults for a new wasmcloud host

**Comment by autodidaddict** [comment]
It's worth pointing out that in the current (`0.18.x`) system, which _does_ perform anti-forgery tokens, it can only detect that an invocation that originated from a host actually originated from that host. The current system does _not_ prevent an intruder from pretending to be a _brand new_ host that just joined the lattice by creating its own host key pair.

**Comment by autodidaddict** [comment]
> It's worth pointing out that in the current (`0.18.x`) system, which _does_ perform anti-forgery tokens, it can only detect that an invocation that originated from a host actually originated from that host. The current system does _not_ prevent an intruder from pretending to be a _brand new_ host that just joined the lattice by creating its own host key pair.

Put another way... In today's system, all someone has to do is ensure that they have a valid nkey encoded the way it's supposed to be encoded (which is super easy if you have access to either the Rust or Go nkeys libraries), and you can create a host key and join the lattice.

The true last line of defense, I believe, does boil down to whether or not an entity has access to the lattice's topic space with their relevant NATS credentials.

**Comment by autodidaddict** [comment]
Closing this issue as we've decided that we will not be doing anti-forgery tokens on the invocations through the RPC mechanism. We may implement additional security measures but this RFC is now closed.
