### ISSUE TITLE
Host should mint NATS user credentials for managed providers

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/wasmcloud-otp#52]
For managed (started as executable files, which could've been downloaded from OCI) providers, the host should mint user credentials for the lattice (if an account seed is available to the host). This is a follow-up to the issue where providers need to get the host data via environment variable #36

**Comment by brooksmtownsend** [comment]
As a point of clarification, this issue calls for minting _User_ credentials, not the _Service_ credentials that should be embedded as part of the claims JWT included with the provider, correct?

**Comment by autodidaddict** [comment]
there's no such thing as "service credentials", there are claims included in the PAR which are claims, not credentials.

**Comment by brooksmtownsend** [comment]
So providers will be required, as before, to have embedded account/service claims. The NATS user credentials will be the authentication method to the host lattice, and the host mints them for the provider so that you can't just start your own provider and anonymously authenticate to the host lattice

**Comment by autodidaddict** [comment]
Not necessarily anonymously, but in a way where you as the provider author don't care what the credentials are.
